{
 "title": "Application Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Web Pods Running",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(prober_probe_total{pod=~\"web-deployment-.*\", container=\"web\", result=\"successful\", probe_type=\"Liveness\"}) by (pod))"
    }
   ]
  },
  {
   "title": "Payment Primary Pods Running",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count(prober_probe_total{pod=~\"api-primary-.*\", container=\"api\", result=\"successful\", probe_type=\"Liveness\"}) by (pod))"
    }
   ]
  },
  {
   "title": "Payment Canary Pods Running",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count(prober_probe_total{pod!~\"api-primary-.*\", container=\"api\", result=\"successful\", probe_type=\"Liveness\"}) by (pod))"
    }
   ]
  },
  {
   "title": "Web Downstream Response",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_listener_http_downstream_rq_xx{local_cluster=\"ingress-gateway\", envoy_listener_address=\"0.0.0.0_18080\"}[$__rate_interval])) by (envoy_response_code_class)",
     "legendFormat": "Response Code {{envoy_response_code_class}}xx"
    }
   ]
  },
  {
   "title": "Downstream error count",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(envoy_listener_http_downstream_rq_xx{local_cluster=\"ingress-gateway\", envoy_listener_address=\"0.0.0.0_18080\", envoy_response_code_class=\"5\"}[$__rate_interval]),1))"
    }
   ]
  },
  {
   "title": "API Request per Second",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (envoy_response_code) (rate(envoy_cluster_upstream_rq{pod!~\"api-primary.*\", namespace=\"default\", envoy_cluster_name=\"local_app\", pod=~\"api.*\"}[$__rate_interval]))",
     "legendFormat": "Canary - {{envoy_response_code}}"
    },
    {
     "expr": "sum by (envoy_response_code) (rate(envoy_cluster_upstream_rq{pod=~\"api-primary.*\", namespace=\"default\", envoy_cluster_name=\"local_app\", pod=~\"api.*\"}[$__rate_interval]))",
     "legendFormat": "Primary - {{envoy_response_code}}"
    }
   ]
  },
  {
   "title": "Retries per Second",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_retry_upstream_rq{consul_destination_service=\"api\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Web Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "{app=\"web\"}"
    }
   ]
  },
  {
   "title": "API Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "{app=~\"api.*\"}"
    }
   ]
  }
 ]
}